files: ^quakemigrate/
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-added-large-files
  - id: check-toml
  - id: check-json
  - id: pretty-format-json
    args: [--autofix]
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.1.3'
  hooks:
    # Run the Ruff linter
    - id: ruff
    # Run the Ruff formatter
    - id: ruff-format
