station_file = "inputs/iceland.sta"
lut_file = "outputs/example.lut"
run_name = "example_run"
log_level = "info"

[archive]
waveform_data = "inputs/mSEED"
archive_format = "YEAR/JD/*_STATION_*"

[scan]
starttime = "2014-06-29T18:41:55.0"
endtime = "2014-06-29T18:42:20.0"
timestep = 0.75
threads = 4

[onset]
name = "STALTA-classic"
sampling_rate = 500
phases = ["P", "S"]

[onset.bandpass_filters]
P = [10, 125, 4]
S = [10, 125, 4]

[onset.sta_lta_windows]
P = [0.01, 0.25]
S = [0.05, 0.5]
