station_file = "inputs/iceland_stations.txt"
lut_file = "outputs/example.lut"
run_name = "example_run"
log_level = "info"

[archive]
waveform_data = "inputs/mSEED"
archive_format = "YEAR/JD/*_STATION_*"

[scan]
starttime = "2014-06-29T18:42:05.0"
endtime = "2014-06-29T18:42:15.0"
marginal_window = 0.06
threads = 4
plot_event_summary = true
write_cut_waveforms = true

[onset]
name = "STALTA-centred"
sampling_rate = 250
phases = ["P", "S"]

[onset.bandpass_filters]
P = [10, 124, 4]
S = [10, 124, 4]

[onset.sta_lta_windows]
P = [0.01, 0.25]
S = [0.05, 0.5]

[picker]
name = "Gaussian"
plot_picks = true
