[lut]
file = "luts/<lut-name>.lut"

[trigger]
starttime = "YYYY-mm-ddTHH:MM:SS.0"  # Can be any format compatible with obspy.UTCDateTime
endtime = "YYYY-mm-ddTHH:MM:SS.0"  # Can be any format compatible with obspy.UTCDateTime
marginal_window = 0.1  # In seconds, see docs for more info
min_event_interval = 0.2  # In seconds, see docs for more info
normalise_coalescence = true

[threshold]
# Static threshold
method = "static"
static_threshold = 2.0  # See docs for more info

# Dynamic threshold - MAD
# method = "mad"
# mad_window_length = 3600.0  # In seconds, see docs for more info
# mad_multiplier = 8.0  # See docs for more info

# Dynamic threshold - median ratio
# method = "median_ratio"
# mad_window_length = 3600.0  # In seconds, see docs for more info
# mad_multiplier = 1.2  # See docs for more info
