lut_file = "outputs/example.lut"
run_name = "example_run"
log_level = "info"

[trigger]
starttime = "2014-06-29T18:42:05.0"
endtime = "2014-06-29T18:42:15.0"
marginal_window = 0.06
min_event_interval = 0.12
normalise_coalescence = true
interactive_plot = false

[threshold]
# Static threshold
method = "static"
static_threshold = 1.8
# Dynamic threshold - MAD
# method = "mad"
# mad_window_length = 7200.0
# mad_multiplier = 8.0
